# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 06:05
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
