# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20181211_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='article',
            name='mod_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
