# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20181211_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
