# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20181211_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mod_date',
            field=models.DateTimeField(default=None),
        ),
    ]
