# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20181211_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/myblog/upload'),
        ),
    ]
