# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20181215_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='myblog/image/1.png', null=True, upload_to='myblog\\image'),
        ),
    ]
